// Stable declaration boundary around code generated by SpacetimeDB.

export type CameraRow = {
  id: string; name: string; latitude: number; longitude: number;
  sourceType: string; streamUrl?: string; status: string; lastSeenAt?: number;
};
export type ObservationRow = {
  id: string; cameraId: string; type: string; confidence: number; timestamp: number;
  evidenceUrl?: string; bbox?: { x: number; y: number; width: number; height: number };
};
export type IncidentRow = {
  id: string; cameraId: string; type: string; status: string; confidence: number;
  latitude: number; longitude: number; firstSeenAt: number; lastSeenAt: number;
  confirmedAt?: number; resolvedAt?: number;
};
export type WatchRow = {
  id: string; spaceId: string; senderId: string; placeLabel: string;
  latitude: number; longitude: number; radiusKm: number; active: boolean; createdAt: number;
};
export type AlertRow = {
  id: string; incidentId: string; watchId: string; status: string; createdAt: number;
  sentAt?: number; providerMessageId?: string; error?: string;
};
export type InboundReceiptRow = {
  messageId: string; spaceId: string; senderId: string; receivedAt: number; contentType: string;
};

export type RowCallback<Row> = (row: Row) => void;
export type RowTable<Row> = {
  iter(): IterableIterator<Row>;
  onInsert(callback: (context: unknown, row: Row) => void): void;
  removeOnInsert(callback: (context: unknown, row: Row) => void): void;
  onUpdate(callback: (context: unknown, oldRow: Row, newRow: Row) => void): void;
  removeOnUpdate(callback: (context: unknown, oldRow: Row, newRow: Row) => void): void;
  onDelete(callback: (context: unknown, row: Row) => void): void;
  removeOnDelete(callback: (context: unknown, row: Row) => void): void;
};

export type GeneratedSubscriptionBuilder = {
  onApplied(callback: () => void): GeneratedSubscriptionBuilder;
  onError(callback: (context: unknown) => void): GeneratedSubscriptionBuilder;
  subscribeToAllTables(): void;
};

export type GeneratedDbConnection = {
  db: {
    camera: RowTable<CameraRow>;
    observation: RowTable<ObservationRow>;
    incident: RowTable<IncidentRow>;
    alert: RowTable<AlertRow>;
    watch: RowTable<WatchRow>;
  };
  reducers: {
    registerCamera(args: { camera: CameraRow }): Promise<void>;
    setCameraStatus(args: { cameraId: string; status: string; lastSeenAt: number }): Promise<void>;
    publishObservation(args: { observation: ObservationRow }): Promise<void>;
    confirmIncident(args: { id: string; confirmedAt: number }): Promise<void>;
    dismissIncident(args: { id: string }): Promise<void>;
    resolveIncident(args: { id: string; resolvedAt: number }): Promise<void>;
    createWatch(args: { input: WatchRow }): Promise<void>;
    deactivateWatchesForSender(args: { senderId: string }): Promise<void>;
    claimInboundMessage(args: { receipt: InboundReceiptRow }): Promise<void>;
    createAlert(args: { incidentId: string; watchId: string }): Promise<void>;
    claimAlert(args: { alertId: string }): Promise<void>;
    markAlertSent(args: { alertId: string; providerMessageId: string; sentAt: number }): Promise<void>;
    markAlertFailed(args: { alertId: string; error: string }): Promise<void>;
  };
  subscriptionBuilder(): GeneratedSubscriptionBuilder;
  disconnect(): void;
};

export type GeneratedDbConnectionBuilder = {
  withUri(uri: string): GeneratedDbConnectionBuilder;
  withDatabaseName(database: string): GeneratedDbConnectionBuilder;
  withToken(token?: string): GeneratedDbConnectionBuilder;
  onConnect(callback: (connection: GeneratedDbConnection) => void): GeneratedDbConnectionBuilder;
  onConnectError(callback: (context: unknown, error: Error) => void): GeneratedDbConnectionBuilder;
  build(): GeneratedDbConnection;
};

export declare const DbConnection: {
  builder(): GeneratedDbConnectionBuilder;
};
