// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  incidentId: __t.string().primaryKey().name("incident_id"),
  title: __t.string(),
  description: __t.string(),
  radiusKm: __t.f64().name("radius_km"),
  reportedBy: __t.string().name("reported_by"),
  reportedAt: __t.f64().name("reported_at"),
});
