// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  cameraId: __t.string().name("camera_id"),
  type: __t.string(),
  status: __t.string(),
  confidence: __t.f64(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  firstSeenAt: __t.f64().name("first_seen_at"),
  lastSeenAt: __t.f64().name("last_seen_at"),
  confirmedAt: __t.option(__t.f64()).name("confirmed_at"),
  resolvedAt: __t.option(__t.f64()).name("resolved_at"),
});
