// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Alert = __t.object("Alert", {
  id: __t.string(),
  incidentId: __t.string(),
  watchId: __t.string(),
  status: __t.string(),
  createdAt: __t.f64(),
  sentAt: __t.option(__t.f64()),
  providerMessageId: __t.option(__t.string()),
  error: __t.option(__t.string()),
});
export type Alert = __Infer<typeof Alert>;

export const AlertInput = __t.object("AlertInput", {
  id: __t.string(),
  incidentId: __t.string(),
  watchId: __t.string(),
  status: __t.string(),
  createdAt: __t.f64(),
  sentAt: __t.option(__t.f64()),
  providerMessageId: __t.option(__t.string()),
  error: __t.option(__t.string()),
});
export type AlertInput = __Infer<typeof AlertInput>;

export const BoundingBox = __t.object("BoundingBox", {
  x: __t.f64(),
  y: __t.f64(),
  width: __t.f64(),
  height: __t.f64(),
});
export type BoundingBox = __Infer<typeof BoundingBox>;

export const Camera = __t.object("Camera", {
  id: __t.string(),
  name: __t.string(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  sourceType: __t.string(),
  streamUrl: __t.option(__t.string()),
  status: __t.string(),
  lastSeenAt: __t.option(__t.f64()),
});
export type Camera = __Infer<typeof Camera>;

export const CameraInput = __t.object("CameraInput", {
  id: __t.string(),
  name: __t.string(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  sourceType: __t.string(),
  streamUrl: __t.option(__t.string()),
  status: __t.string(),
  lastSeenAt: __t.option(__t.f64()),
});
export type CameraInput = __Infer<typeof CameraInput>;

export const Incident = __t.object("Incident", {
  id: __t.string(),
  cameraId: __t.string(),
  type: __t.string(),
  status: __t.string(),
  confidence: __t.f64(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  firstSeenAt: __t.f64(),
  lastSeenAt: __t.f64(),
  confirmedAt: __t.option(__t.f64()),
  resolvedAt: __t.option(__t.f64()),
});
export type Incident = __Infer<typeof Incident>;

export const IncidentInput = __t.object("IncidentInput", {
  id: __t.string(),
  cameraId: __t.string(),
  type: __t.string(),
  status: __t.string(),
  confidence: __t.f64(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  firstSeenAt: __t.f64(),
  lastSeenAt: __t.f64(),
  confirmedAt: __t.option(__t.f64()),
  resolvedAt: __t.option(__t.f64()),
});
export type IncidentInput = __Infer<typeof IncidentInput>;

export const ModuleConfig = __t.object("ModuleConfig", {
  ownerIdentity: __t.identity(),
});
export type ModuleConfig = __Infer<typeof ModuleConfig>;

export const Observation = __t.object("Observation", {
  id: __t.string(),
  cameraId: __t.string(),
  type: __t.string(),
  confidence: __t.f64(),
  timestamp: __t.f64(),
  evidenceUrl: __t.option(__t.string()),
  get bbox() {
    return __t.option(BoundingBox);
  },
});
export type Observation = __Infer<typeof Observation>;

export const ObservationInput = __t.object("ObservationInput", {
  id: __t.string(),
  cameraId: __t.string(),
  type: __t.string(),
  confidence: __t.f64(),
  timestamp: __t.f64(),
  evidenceUrl: __t.option(__t.string()),
  get bbox() {
    return __t.option(BoundingBox);
  },
});
export type ObservationInput = __Infer<typeof ObservationInput>;

export const SpectrumEvent = __t.object("SpectrumEvent", {
  eventId: __t.string(),
  receivedAt: __t.f64(),
});
export type SpectrumEvent = __Infer<typeof SpectrumEvent>;

export const Watch = __t.object("Watch", {
  id: __t.string(),
  userHandle: __t.string(),
  placeLabel: __t.string(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  radiusKm: __t.f64(),
  active: __t.bool(),
  createdAt: __t.f64(),
});
export type Watch = __Infer<typeof Watch>;

export const WatchInput = __t.object("WatchInput", {
  id: __t.string(),
  userHandle: __t.string(),
  placeLabel: __t.string(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  radiusKm: __t.f64(),
  active: __t.bool(),
  createdAt: __t.f64(),
});
export type WatchInput = __Infer<typeof WatchInput>;

