// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  userId: __t.string().primaryKey().name("user_id"),
  spaceId: __t.string().name("space_id"),
  senderId: __t.string().name("sender_id"),
  latitude: __t.f64(),
  longitude: __t.f64(),
  accuracyMeters: __t.option(__t.f64()).name("accuracy_meters"),
  locationUpdatedAt: __t.f64().name("location_updated_at"),
  radiusKm: __t.f64().name("radius_km"),
  alertsEnabled: __t.bool().name("alerts_enabled"),
  createdAt: __t.f64().name("created_at"),
  updatedAt: __t.f64().name("updated_at"),
});
