// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClaimAlertReducer from "../claim_alert_reducer";
import ClaimInboundMessageReducer from "../claim_inbound_message_reducer";
import ConfirmIncidentReducer from "../confirm_incident_reducer";
import CreateAlertReducer from "../create_alert_reducer";
import CreateAlertForProfileReducer from "../create_alert_for_profile_reducer";
import CreateIncidentReducer from "../create_incident_reducer";
import CreateMobilePairingReducer from "../create_mobile_pairing_reducer";
import CreateWatchReducer from "../create_watch_reducer";
import DeactivateWatchesForSenderReducer from "../deactivate_watches_for_sender_reducer";
import DismissIncidentReducer from "../dismiss_incident_reducer";
import InsertAlertReducer from "../insert_alert_reducer";
import InsertWatchReducer from "../insert_watch_reducer";
import MarkAlertFailedReducer from "../mark_alert_failed_reducer";
import MarkAlertSentReducer from "../mark_alert_sent_reducer";
import MobileCheckCredentialReducer from "../mobile_check_credential_reducer";
import MobileSetSharingReducer from "../mobile_set_sharing_reducer";
import MobileUpdateLocationReducer from "../mobile_update_location_reducer";
import PublishObservationReducer from "../publish_observation_reducer";
import RedeemMobilePairingReducer from "../redeem_mobile_pairing_reducer";
import RegisterCameraReducer from "../register_camera_reducer";
import ResolveIncidentReducer from "../resolve_incident_reducer";
import RevokeMobileDeviceReducer from "../revoke_mobile_device_reducer";
import SetAlertsEnabledReducer from "../set_alerts_enabled_reducer";
import SetCameraStatusReducer from "../set_camera_status_reducer";
import SetMobileTrackingForSenderReducer from "../set_mobile_tracking_for_sender_reducer";
import UpdateIncidentDetectionReducer from "../update_incident_detection_reducer";
import UpsertConversationContextReducer from "../upsert_conversation_context_reducer";
import UpsertUserAlertProfileReducer from "../upsert_user_alert_profile_reducer";

export type ClaimAlertParams = __Infer<typeof ClaimAlertReducer>;
export type ClaimInboundMessageParams = __Infer<typeof ClaimInboundMessageReducer>;
export type ConfirmIncidentParams = __Infer<typeof ConfirmIncidentReducer>;
export type CreateAlertParams = __Infer<typeof CreateAlertReducer>;
export type CreateAlertForProfileParams = __Infer<typeof CreateAlertForProfileReducer>;
export type CreateIncidentParams = __Infer<typeof CreateIncidentReducer>;
export type CreateMobilePairingParams = __Infer<typeof CreateMobilePairingReducer>;
export type CreateWatchParams = __Infer<typeof CreateWatchReducer>;
export type DeactivateWatchesForSenderParams = __Infer<typeof DeactivateWatchesForSenderReducer>;
export type DismissIncidentParams = __Infer<typeof DismissIncidentReducer>;
export type InsertAlertParams = __Infer<typeof InsertAlertReducer>;
export type InsertWatchParams = __Infer<typeof InsertWatchReducer>;
export type MarkAlertFailedParams = __Infer<typeof MarkAlertFailedReducer>;
export type MarkAlertSentParams = __Infer<typeof MarkAlertSentReducer>;
export type MobileCheckCredentialParams = __Infer<typeof MobileCheckCredentialReducer>;
export type MobileSetSharingParams = __Infer<typeof MobileSetSharingReducer>;
export type MobileUpdateLocationParams = __Infer<typeof MobileUpdateLocationReducer>;
export type PublishObservationParams = __Infer<typeof PublishObservationReducer>;
export type RedeemMobilePairingParams = __Infer<typeof RedeemMobilePairingReducer>;
export type RegisterCameraParams = __Infer<typeof RegisterCameraReducer>;
export type ResolveIncidentParams = __Infer<typeof ResolveIncidentReducer>;
export type RevokeMobileDeviceParams = __Infer<typeof RevokeMobileDeviceReducer>;
export type SetAlertsEnabledParams = __Infer<typeof SetAlertsEnabledReducer>;
export type SetCameraStatusParams = __Infer<typeof SetCameraStatusReducer>;
export type SetMobileTrackingForSenderParams = __Infer<typeof SetMobileTrackingForSenderReducer>;
export type UpdateIncidentDetectionParams = __Infer<typeof UpdateIncidentDetectionReducer>;
export type UpsertConversationContextParams = __Infer<typeof UpsertConversationContextReducer>;
export type UpsertUserAlertProfileParams = __Infer<typeof UpsertUserAlertProfileReducer>;

